
name: node-starter

services:
  mongodb-primary:
    image: docker.io/bitnami/mongodb:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_BIND_PORT=27017
    volumes:
      - "mongodb:/bitnami/mongodb"
    ports:
      - "${MONGODB_BIND_PORT}:27017"

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb-primary
    environment:
      VCAP_APP_PORT: "8081"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongodb-primary/admin?readPreference=primaryPreferred
      ME_BIND_PORT: "8080"
    restart: always
    ports:
      - "${ME_BIND_PORT}:8081"

  redis:
    image: redis/redis-stack-server
    environment:
      REDIS_ARGS: "--requirepass olFot8RroCYL6t4XFqeBeweU"
      REDIS_BIND_PORT: "6379"
    restart: always
    ports:
      - "${REDIS_BIND_PORT}:6379"
    volumes:
      - "redis:/data"

volumes:
  mongodb:
    driver: local
  redis:
    driver: local
